workflows:
  ios-release:
    name: Flutter iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: QuranApp Key
    environment:
      groups:
        - apple_credentials
      vars:
        BUNDLE_ID: "com.quran.tj.osonbayon"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Set up local properties and dependencies
        script: |
          flutter config --no-enable-swift-package-manager
          flutter precache --ios
          flutter pub get
          flutter build ios --config-only --no-codesign || true
      - name: Configure Pods and dependencies
        script: |
          cd ios && pod install
      - name: Initialize keychain
        script: |
          keychain initialize
      - name: Fetch Apple Certificates and Provisioning Profiles
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Apply Provisioning Profiles
        script: |
          xcode-project use-profiles
      - name: Build Flutter iOS App (IPA)
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - zabirovms@gmail.com
        notify:
          success: true
          failure: true
